### ISSUE TITLE
GMail attachment download not working

### ISSUE THREAD

**Issue by Diegotru** [unintended/download-organizer-chrome-extension#37]
Please help. This is driving me crazy.
I have multiple gmail accounts, and want to get documents from each account downloaded separate in its own folder.
This is my referrer URL: `.*\mail\.google\.com\/mail\/u\/(.).*`
This is my download folder: `gmail/ACCOUNT${referrer:1}/
`
I've tried multiple combinations to see if something is wrong, can't make it work.

Can someone correct it? Thank you!
EDIT: Didn't realize that it was not displaying code correctly. Now it's as I entered

**Comment by unintended** [comment]
I debugged this case and it looks like it's not possible to catch it via referrer or url fields because they are always set to `about:blank` (looks like the download is started by script).
However, I'm releasing 0.3 version that will support finalUrl field and this rule will work on it:

`{"enabled":true,"description":"gmail","finalUrl":"mail\\-attachment\\.googleusercontent\\.com/attachment/u/([0-9]+)/","pattern":"gmail/${finalUrl:1}/"}`

Just wait for the release.

**Comment by Diegotru** [comment]
Thank you!
I thought I was going insane... lol
I'm after that error for days without getting it right.
I'll wait for the release. Thanks again for the solution

**Comment by Diegotru** [comment]
It's working now!
Thank you!
